[project]
name = "brachlearn"
version = "0.1.0"
description = "Brachistochrone-inspired minimum-time learning"
requires-python = ">=3.9"
dependencies = []

[tool.setuptools]
packages = ["src.brachlearn"]
